package entity;
// Generated May 18, 2019 5:01:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Investment generated by hbm2java
 */
public class Investment  implements java.io.Serializable {


     private Integer id;
     private String accountNo;
     private String projectName;
     private String projectLocation;
     private Double totalInvestment;
     private Date startDate;
     private Integer projectDuration;
     private String directortName;
     private String gender;
     private String religion;
     private String dateofBirth;
     private String nidno;
     private String mobileNo;
     private String presentAddress;
     private String parmanetAddress;
     private byte[] picture;

    public Investment() {
    }

    public Investment(String accountNo, String projectName, String projectLocation, Double totalInvestment, Date startDate, Integer projectDuration, String directortName, String gender, String religion, String dateofBirth, String nidno, String mobileNo, String presentAddress, String parmanetAddress, byte[] picture) {
       this.accountNo = accountNo;
       this.projectName = projectName;
       this.projectLocation = projectLocation;
       this.totalInvestment = totalInvestment;
       this.startDate = startDate;
       this.projectDuration = projectDuration;
       this.directortName = directortName;
       this.gender = gender;
       this.religion = religion;
       this.dateofBirth = dateofBirth;
       this.nidno = nidno;
       this.mobileNo = mobileNo;
       this.presentAddress = presentAddress;
       this.parmanetAddress = parmanetAddress;
       this.picture = picture;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAccountNo() {
        return this.accountNo;
    }
    
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }
    public String getProjectName() {
        return this.projectName;
    }
    
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }
    public String getProjectLocation() {
        return this.projectLocation;
    }
    
    public void setProjectLocation(String projectLocation) {
        this.projectLocation = projectLocation;
    }
    public Double getTotalInvestment() {
        return this.totalInvestment;
    }
    
    public void setTotalInvestment(Double totalInvestment) {
        this.totalInvestment = totalInvestment;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Integer getProjectDuration() {
        return this.projectDuration;
    }
    
    public void setProjectDuration(Integer projectDuration) {
        this.projectDuration = projectDuration;
    }
    public String getDirectortName() {
        return this.directortName;
    }
    
    public void setDirectortName(String directortName) {
        this.directortName = directortName;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }
    public String getDateofBirth() {
        return this.dateofBirth;
    }
    
    public void setDateofBirth(String dateofBirth) {
        this.dateofBirth = dateofBirth;
    }
    public String getNidno() {
        return this.nidno;
    }
    
    public void setNidno(String nidno) {
        this.nidno = nidno;
    }
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }
    public String getPresentAddress() {
        return this.presentAddress;
    }
    
    public void setPresentAddress(String presentAddress) {
        this.presentAddress = presentAddress;
    }
    public String getParmanetAddress() {
        return this.parmanetAddress;
    }
    
    public void setParmanetAddress(String parmanetAddress) {
        this.parmanetAddress = parmanetAddress;
    }
    public byte[] getPicture() {
        return this.picture;
    }
    
    public void setPicture(byte[] picture) {
        this.picture = picture;
    }




}


