package entity;
// Generated May 18, 2019 5:01:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Person generated by hbm2java
 */
public class Person  implements java.io.Serializable {


     private Integer id;
     private String accountNo;
     private String fromNo;
     private String cardNo;
     private Date admissionDate;
     private String name;
     private String motherName;
     private String fatherHusbendName;
     private String gender;
     private String religion;
     private String dateofBirth;
     private String nidno;
     private String mobileNo;
     private String presentAddress;
     private String parmanetAddress;
     private String savingType;
     private Integer annunity;
     private String nomineName;
     private String relations;
     private Integer share;
     private byte[] picture;

    public Person() {
    }

    public Person(String accountNo, String fromNo, String cardNo, Date admissionDate, String name, String motherName, String fatherHusbendName, String gender, String religion, String dateofBirth, String nidno, String mobileNo, String presentAddress, String parmanetAddress, String savingType, Integer annunity, String nomineName, String relations, Integer share, byte[] picture) {
       this.accountNo = accountNo;
       this.fromNo = fromNo;
       this.cardNo = cardNo;
       this.admissionDate = admissionDate;
       this.name = name;
       this.motherName = motherName;
       this.fatherHusbendName = fatherHusbendName;
       this.gender = gender;
       this.religion = religion;
       this.dateofBirth = dateofBirth;
       this.nidno = nidno;
       this.mobileNo = mobileNo;
       this.presentAddress = presentAddress;
       this.parmanetAddress = parmanetAddress;
       this.savingType = savingType;
       this.annunity = annunity;
       this.nomineName = nomineName;
       this.relations = relations;
       this.share = share;
       this.picture = picture;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAccountNo() {
        return this.accountNo;
    }
    
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }
    public String getFromNo() {
        return this.fromNo;
    }
    
    public void setFromNo(String fromNo) {
        this.fromNo = fromNo;
    }
    public String getCardNo() {
        return this.cardNo;
    }
    
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }
    public Date getAdmissionDate() {
        return this.admissionDate;
    }
    
    public void setAdmissionDate(Date admissionDate) {
        this.admissionDate = admissionDate;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getMotherName() {
        return this.motherName;
    }
    
    public void setMotherName(String motherName) {
        this.motherName = motherName;
    }
    public String getFatherHusbendName() {
        return this.fatherHusbendName;
    }
    
    public void setFatherHusbendName(String fatherHusbendName) {
        this.fatherHusbendName = fatherHusbendName;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }
    public String getDateofBirth() {
        return this.dateofBirth;
    }
    
    public void setDateofBirth(String dateofBirth) {
        this.dateofBirth = dateofBirth;
    }
    public String getNidno() {
        return this.nidno;
    }
    
    public void setNidno(String nidno) {
        this.nidno = nidno;
    }
    public String getMobileNo() {
        return this.mobileNo;
    }
    
    public void setMobileNo(String mobileNo) {
        this.mobileNo = mobileNo;
    }
    public String getPresentAddress() {
        return this.presentAddress;
    }
    
    public void setPresentAddress(String presentAddress) {
        this.presentAddress = presentAddress;
    }
    public String getParmanetAddress() {
        return this.parmanetAddress;
    }
    
    public void setParmanetAddress(String parmanetAddress) {
        this.parmanetAddress = parmanetAddress;
    }
    public String getSavingType() {
        return this.savingType;
    }
    
    public void setSavingType(String savingType) {
        this.savingType = savingType;
    }
    public Integer getAnnunity() {
        return this.annunity;
    }
    
    public void setAnnunity(Integer annunity) {
        this.annunity = annunity;
    }
    public String getNomineName() {
        return this.nomineName;
    }
    
    public void setNomineName(String nomineName) {
        this.nomineName = nomineName;
    }
    public String getRelations() {
        return this.relations;
    }
    
    public void setRelations(String relations) {
        this.relations = relations;
    }
    public Integer getShare() {
        return this.share;
    }
    
    public void setShare(Integer share) {
        this.share = share;
    }
    public byte[] getPicture() {
        return this.picture;
    }
    
    public void setPicture(byte[] picture) {
        this.picture = picture;
    }




}


