package entity;
// Generated May 18, 2019 5:01:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Summary generated by hbm2java
 */
public class Summary  implements java.io.Serializable {


     private Integer id;
     private String accountNo;
     private String name;
     private String savingType;
     private Integer annunity;
     private Date date;
     private Integer totalDeposit;
     private Integer totalWithdraw;
     private Integer balance;
     private Integer installmentNo;
     private Date coverDate;
     private Integer due;

    public Summary() {
    }

    public Summary(String accountNo, String name, String savingType, Integer annunity, Date date, Integer totalDeposit, Integer totalWithdraw, Integer balance, Integer installmentNo, Date coverDate, Integer due) {
       this.accountNo = accountNo;
       this.name = name;
       this.savingType = savingType;
       this.annunity = annunity;
       this.date = date;
       this.totalDeposit = totalDeposit;
       this.totalWithdraw = totalWithdraw;
       this.balance = balance;
       this.installmentNo = installmentNo;
       this.coverDate = coverDate;
       this.due = due;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getAccountNo() {
        return this.accountNo;
    }
    
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSavingType() {
        return this.savingType;
    }
    
    public void setSavingType(String savingType) {
        this.savingType = savingType;
    }
    public Integer getAnnunity() {
        return this.annunity;
    }
    
    public void setAnnunity(Integer annunity) {
        this.annunity = annunity;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Integer getTotalDeposit() {
        return this.totalDeposit;
    }
    
    public void setTotalDeposit(Integer totalDeposit) {
        this.totalDeposit = totalDeposit;
    }
    public Integer getTotalWithdraw() {
        return this.totalWithdraw;
    }
    
    public void setTotalWithdraw(Integer totalWithdraw) {
        this.totalWithdraw = totalWithdraw;
    }
    public Integer getBalance() {
        return this.balance;
    }
    
    public void setBalance(Integer balance) {
        this.balance = balance;
    }
    public Integer getInstallmentNo() {
        return this.installmentNo;
    }
    
    public void setInstallmentNo(Integer installmentNo) {
        this.installmentNo = installmentNo;
    }
    public Date getCoverDate() {
        return this.coverDate;
    }
    
    public void setCoverDate(Date coverDate) {
        this.coverDate = coverDate;
    }
    public Integer getDue() {
        return this.due;
    }
    
    public void setDue(Integer due) {
        this.due = due;
    }




}


