package entity;
// Generated May 18, 2019 5:01:16 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Transtion generated by hbm2java
 */
public class Transtion  implements java.io.Serializable {


     private Integer id;
     private Date date;
     private String accountNo;
     private String name;
     private String slipNo;
     private Integer deposit;
     private Integer withdraw;

    public Transtion() {
    }

    public Transtion(Date date, String accountNo, String name, String slipNo, Integer deposit, Integer withdraw) {
       this.date = date;
       this.accountNo = accountNo;
       this.name = name;
       this.slipNo = slipNo;
       this.deposit = deposit;
       this.withdraw = withdraw;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public String getAccountNo() {
        return this.accountNo;
    }
    
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSlipNo() {
        return this.slipNo;
    }
    
    public void setSlipNo(String slipNo) {
        this.slipNo = slipNo;
    }
    public Integer getDeposit() {
        return this.deposit;
    }
    
    public void setDeposit(Integer deposit) {
        this.deposit = deposit;
    }
    public Integer getWithdraw() {
        return this.withdraw;
    }
    
    public void setWithdraw(Integer withdraw) {
        this.withdraw = withdraw;
    }




}


